/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package calculadora;

/**
 * @author GERARDO OBEID GUZMÁN
 * @author JOSE PABLO ANTÚNEZ
 * @author DIEGO GARCÍA GAYOU
 * @author WILFREDO SALAZAR
 */
public class CalculadoraGUI extends javax.swing.JFrame {

    /**
     * Creates new form CalculadoraGUI
     */
    public CalculadoraGUI() {
        initComponents();
    }
    private double VALUE_E = 2.71828;
    private double VALUE_PI = 3.1416;
    private String textoPantalla;
    private double respuesta;
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jb6 = new javax.swing.JButton();
        jb4 = new javax.swing.JButton();
        jb7 = new javax.swing.JButton();
        jbSuma = new javax.swing.JButton();
        jb1 = new javax.swing.JButton();
        jb0 = new javax.swing.JButton();
        jbBorrar = new javax.swing.JButton();
        jbPot = new javax.swing.JButton();
        jbRespuesta = new javax.swing.JButton();
        jb8 = new javax.swing.JButton();
        jbResta = new javax.swing.JButton();
        jb5 = new javax.swing.JButton();
        jb2 = new javax.swing.JButton();
        jbPunto = new javax.swing.JButton();
        jb3 = new javax.swing.JButton();
        jbDiv = new javax.swing.JButton();
        jb9 = new javax.swing.JButton();
        jbPi = new javax.swing.JButton();
        jbMult = new javax.swing.JButton();
        jtfPantalla = new javax.swing.JTextField();
        jbParentAbr = new javax.swing.JButton();
        jbParentCerr = new javax.swing.JButton();
        jbBorrarTodo = new javax.swing.JButton();
        jbE = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("CALCULATOR");

        jb6.setBackground(new java.awt.Color(255, 255, 153));
        jb6.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jb6.setText("6");
        jb6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb6ActionPerformed(evt);
            }
        });

        jb4.setBackground(new java.awt.Color(255, 255, 153));
        jb4.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jb4.setText("4");
        jb4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb4ActionPerformed(evt);
            }
        });

        jb7.setBackground(new java.awt.Color(255, 255, 153));
        jb7.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jb7.setText("7");
        jb7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb7ActionPerformed(evt);
            }
        });

        jbSuma.setBackground(new java.awt.Color(102, 255, 255));
        jbSuma.setFont(new java.awt.Font("MS PGothic", 1, 17)); // NOI18N
        jbSuma.setText("+");
        jbSuma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSumaActionPerformed(evt);
            }
        });

        jb1.setBackground(new java.awt.Color(255, 255, 153));
        jb1.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jb1.setText("1");
        jb1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb1ActionPerformed(evt);
            }
        });

        jb0.setBackground(new java.awt.Color(255, 255, 153));
        jb0.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jb0.setText("0");
        jb0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb0ActionPerformed(evt);
            }
        });

        jbBorrar.setBackground(new java.awt.Color(255, 153, 153));
        jbBorrar.setFont(new java.awt.Font("MS PGothic", 1, 14)); // NOI18N
        jbBorrar.setText("c");
        jbBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbBorrarActionPerformed(evt);
            }
        });

        jbPot.setBackground(new java.awt.Color(102, 255, 255));
        jbPot.setFont(new java.awt.Font("MS PGothic", 1, 14)); // NOI18N
        jbPot.setText("^");
        jbPot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbPotActionPerformed(evt);
            }
        });

        jbRespuesta.setBackground(new java.awt.Color(0, 204, 0));
        jbRespuesta.setFont(new java.awt.Font("Gill Sans MT", 1, 14)); // NOI18N
        jbRespuesta.setText("=");
        jbRespuesta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbRespuestaActionPerformed(evt);
            }
        });

        jb8.setBackground(new java.awt.Color(255, 255, 153));
        jb8.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jb8.setText("8");
        jb8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb8ActionPerformed(evt);
            }
        });

        jbResta.setBackground(new java.awt.Color(102, 255, 255));
        jbResta.setFont(new java.awt.Font("MS PGothic", 1, 16)); // NOI18N
        jbResta.setText("-");
        jbResta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbRestaActionPerformed(evt);
            }
        });

        jb5.setBackground(new java.awt.Color(255, 255, 153));
        jb5.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jb5.setText("5");
        jb5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb5ActionPerformed(evt);
            }
        });

        jb2.setBackground(new java.awt.Color(255, 255, 153));
        jb2.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jb2.setText("2");
        jb2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb2ActionPerformed(evt);
            }
        });

        jbPunto.setBackground(new java.awt.Color(0, 204, 204));
        jbPunto.setFont(new java.awt.Font("MS PGothic", 1, 24)); // NOI18N
        jbPunto.setText(".");
        jbPunto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbPuntoActionPerformed(evt);
            }
        });

        jb3.setBackground(new java.awt.Color(255, 255, 153));
        jb3.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jb3.setText("3");
        jb3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb3ActionPerformed(evt);
            }
        });

        jbDiv.setBackground(new java.awt.Color(102, 255, 255));
        jbDiv.setFont(new java.awt.Font("MS PGothic", 1, 14)); // NOI18N
        jbDiv.setText("/");
        jbDiv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbDivActionPerformed(evt);
            }
        });

        jb9.setBackground(new java.awt.Color(255, 255, 153));
        jb9.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jb9.setText("9");
        jb9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb9ActionPerformed(evt);
            }
        });

        jbPi.setBackground(new java.awt.Color(255, 255, 153));
        jbPi.setFont(new java.awt.Font("MS PGothic", 1, 12)); // NOI18N
        jbPi.setText("π");
        jbPi.setToolTipText("");
        jbPi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbPiActionPerformed(evt);
            }
        });

        jbMult.setBackground(new java.awt.Color(102, 255, 255));
        jbMult.setFont(new java.awt.Font("MS PGothic", 1, 16)); // NOI18N
        jbMult.setText("*");
        jbMult.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbMultActionPerformed(evt);
            }
        });

        jtfPantalla.setEditable(false);
        jtfPantalla.setFont(new java.awt.Font("MS PGothic", 1, 18)); // NOI18N
        jtfPantalla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfPantallaActionPerformed(evt);
            }
        });

        jbParentAbr.setBackground(new java.awt.Color(0, 204, 204));
        jbParentAbr.setFont(new java.awt.Font("MS PGothic", 1, 14)); // NOI18N
        jbParentAbr.setText("(");
        jbParentAbr.setToolTipText("");
        jbParentAbr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbParentAbrActionPerformed(evt);
            }
        });

        jbParentCerr.setBackground(new java.awt.Color(0, 204, 204));
        jbParentCerr.setFont(new java.awt.Font("MS PGothic", 1, 14)); // NOI18N
        jbParentCerr.setText(")");
        jbParentCerr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbParentCerrActionPerformed(evt);
            }
        });

        jbBorrarTodo.setBackground(new java.awt.Color(255, 153, 153));
        jbBorrarTodo.setFont(new java.awt.Font("MS PGothic", 1, 10)); // NOI18N
        jbBorrarTodo.setText("AC");
        jbBorrarTodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbBorrarTodoActionPerformed(evt);
            }
        });

        jbE.setBackground(new java.awt.Color(255, 255, 153));
        jbE.setFont(new java.awt.Font("MS PGothic", 1, 14)); // NOI18N
        jbE.setText("e");
        jbE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbEActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtfPantalla, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jbSuma, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jb4, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jb1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jb0, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jb7, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jb5, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jb2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jbPunto, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jb8, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jbDiv, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jbMult, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jb6, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jb3, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jb9, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbBorrar, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jbResta, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jbPot, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(jbE, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jbBorrarTodo, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jbParentAbr, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jbPi, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                                    .addComponent(jbParentCerr, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jbRespuesta, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jtfPantalla, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jbMult, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbDiv, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbResta, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbPot, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jb8, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jb9, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jb5, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jb6, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jbPi, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jb2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jb3, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jbParentAbr, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jbBorrarTodo, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jbE, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbRespuesta, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jbSuma, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jb7, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jb4, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jb1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jbBorrar, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jbParentCerr, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jbPunto, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jb0, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(49, 49, 49))
        );

        jbBorrar.getAccessibleContext().setAccessibleName("AC");
        jbPi.getAccessibleContext().setAccessibleName("jbPi");
        jbParentAbr.getAccessibleContext().setAccessibleName("jbParenthesisOpen");
        jbParentCerr.getAccessibleContext().setAccessibleName("jbParenthesisClose");
        jbBorrarTodo.getAccessibleContext().setAccessibleName("jbAc");
        jbBorrarTodo.getAccessibleContext().setAccessibleDescription("");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jb4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb4ActionPerformed
        appendToDisplayText("4");
    }//GEN-LAST:event_jb4ActionPerformed

    private void jbPotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbPotActionPerformed
        appendToDisplayText("^");
    }//GEN-LAST:event_jbPotActionPerformed

    private void jbRespuestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbRespuestaActionPerformed
        textoPantalla = jtfPantalla.getText();
        try{
            respuesta = Calculadora.evaluate(Calculadora.infijoAPostfijo(textoPantalla));
            jtfPantalla.setText(""+respuesta);
        }
        catch(Exception e){
            jtfPantalla.setText(e.getMessage());  
        }
    }//GEN-LAST:event_jbRespuestaActionPerformed

    private void jbSumaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSumaActionPerformed
       appendToDisplayText("+");
    }//GEN-LAST:event_jbSumaActionPerformed

    private void jbPiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbPiActionPerformed
        appendToDisplayText(""+VALUE_PI);
    }//GEN-LAST:event_jbPiActionPerformed

    private void jbBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbBorrarActionPerformed
        // TODO add your handling code here:
        textoPantalla = jtfPantalla.getText();
        if (textoPantalla.length()>=1)
            jtfPantalla.setText(textoPantalla.substring(0,textoPantalla.length()-1));
    }//GEN-LAST:event_jbBorrarActionPerformed

    private void jbParentAbrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbParentAbrActionPerformed
        appendToDisplayText("(");
    }//GEN-LAST:event_jbParentAbrActionPerformed

    private void jbParentCerrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbParentCerrActionPerformed
        appendToDisplayText(")");
    }//GEN-LAST:event_jbParentCerrActionPerformed

    private void jbBorrarTodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbBorrarTodoActionPerformed
        jtfPantalla.setText("");
    }//GEN-LAST:event_jbBorrarTodoActionPerformed

    private void jbEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbEActionPerformed
        appendToDisplayText(""+VALUE_E);
        
    }//GEN-LAST:event_jbEActionPerformed

    private void jtfPantallaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfPantallaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfPantallaActionPerformed

    private void jb7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb7ActionPerformed
        appendToDisplayText("7");
    }//GEN-LAST:event_jb7ActionPerformed
                                
    private void jb0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb0ActionPerformed
        appendToDisplayText("0");
    }//GEN-LAST:event_jb0ActionPerformed

    private void jb1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb1ActionPerformed
        appendToDisplayText("1");
    }//GEN-LAST:event_jb1ActionPerformed

    private void jb8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb8ActionPerformed
        appendToDisplayText("8");
    }//GEN-LAST:event_jb8ActionPerformed

    private void jb9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb9ActionPerformed
        appendToDisplayText("9");
    }//GEN-LAST:event_jb9ActionPerformed

    private void jb5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb5ActionPerformed
        appendToDisplayText("5");
    }//GEN-LAST:event_jb5ActionPerformed

    private void jb6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb6ActionPerformed
        appendToDisplayText("6");
    }//GEN-LAST:event_jb6ActionPerformed

    private void jb2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb2ActionPerformed
        appendToDisplayText("2");
    }//GEN-LAST:event_jb2ActionPerformed

    private void jb3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb3ActionPerformed
        appendToDisplayText("3");
    }//GEN-LAST:event_jb3ActionPerformed

    private void jbPuntoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbPuntoActionPerformed
        appendToDisplayText(".");
    }//GEN-LAST:event_jbPuntoActionPerformed

    private void jbDivActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbDivActionPerformed
        appendToDisplayText("/");
    }//GEN-LAST:event_jbDivActionPerformed

    private void jbMultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbMultActionPerformed
        appendToDisplayText("*");
    }//GEN-LAST:event_jbMultActionPerformed

    private void jbRestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbRestaActionPerformed
        appendToDisplayText("-");
    }//GEN-LAST:event_jbRestaActionPerformed

    private void appendToDisplayText(String newText){
         textoPantalla = jtfPantalla.getText();
         jtfPantalla.setText(textoPantalla+newText);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CalculadoraGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CalculadoraGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CalculadoraGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CalculadoraGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CalculadoraGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jb0;
    private javax.swing.JButton jb1;
    private javax.swing.JButton jb2;
    private javax.swing.JButton jb3;
    private javax.swing.JButton jb4;
    private javax.swing.JButton jb5;
    private javax.swing.JButton jb6;
    private javax.swing.JButton jb7;
    private javax.swing.JButton jb8;
    private javax.swing.JButton jb9;
    private javax.swing.JButton jbBorrar;
    private javax.swing.JButton jbBorrarTodo;
    private javax.swing.JButton jbDiv;
    private javax.swing.JButton jbE;
    private javax.swing.JButton jbMult;
    private javax.swing.JButton jbParentAbr;
    private javax.swing.JButton jbParentCerr;
    private javax.swing.JButton jbPi;
    private javax.swing.JButton jbPot;
    private javax.swing.JButton jbPunto;
    private javax.swing.JButton jbRespuesta;
    private javax.swing.JButton jbResta;
    private javax.swing.JButton jbSuma;
    private javax.swing.JTextField jtfPantalla;
    // End of variables declaration//GEN-END:variables
}
